AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  hokatsu-app

  Sample SAM Template for hokatsu-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
    MemorySize: 384

Resources:
  Ota:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: ota
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(30 8 ? * MON-FRI *)
      Environment:
        Variables:
          SQS_URL: !GetAtt NotificationQueue.QueueUrl
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda/ota
      DockerTag: python3.10-v1
  NotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NotificationQueue
      VisibilityTimeout: 600
  Notification:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: notification
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
        - AmazonSESFullAccess
      Handler: main
      Runtime: go1.x
      CodeUri: ./lambda/notification
      Environment:
        Variables:
          SQS_QUEUE_URL: !GetAtt NotificationQueue.QueueUrl
      Events:
        Trigger:
          Type: SQS
          Properties:
            Queue: !GetAtt NotificationQueue.Arn
