AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  hokatsu-app

  Sample SAM Template for hokatsu-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 384

Resources:
  Ota:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies: AmazonDynamoDBFullAccess
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(30 14 ? * TUE *)
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda
      DockerTag: python3.10-v1
